[theme]
primaryColor="#3b82f6"              # Curio Lab blue (matches bear goggles)
backgroundColor="#f8fafc"           # soft white background
secondaryBackgroundColor="#e0f2fe" # light blue panels (matches lab theme)
textColor="#1e3a8a"                 # deep blue text
font="sans serif"
